### ISSUE TITLE
socket error python 2.7

### ISSUE THREAD

**Issue by jaanaltosaar** [sfalkner/pySMAC#17] opened 2016-07-09 15:43 UTC
`~/projects/scratch/pySMAC/examples   master  python branin_example.py
Traceback (most recent call last):
  File "build/bdist.macosx-10.6-x86_64/egg/pysmac/remote_smac.py", line 274, in remote_smac_function
    config_dict = smac.next_configuration()
  File "build/bdist.macosx-10.6-x86_64/egg/pysmac/remote_smac.py", line 195, in next_configuration
    config_str = fconn.readline()
  File "/Users/jaanaltosaar/anaconda2/lib/python2.7/socket.py", line 451, in readline
    data = self._sock.recv(self._rbufsize)
error: [Errno 35] Resource temporarily unavailable
Lowest function value found: 179769313486231570814527423731704356798070567525844996598917476803157260780028538760589558632766878171540458953514382464234321326889464182768467546703537516986049910576551282076245490090389328944075868508455133942304583236903222948165808559332123348274797826204144723168738177180919299881250404026184124858368.000000
Parameter setting {'x2': -1.0, 'x3': 1, 'x1': 1.0}
 ~/projects/scratch/pySMAC/examples   master `

Could this be related? https://bugs.python.org/msg64566

Would love to try pySMAC - thank you!

**Comment by sfalkner** [comment] 2016-07-11 09:45
Hello @altosaar ,

thanks for your interest in pySMAC. 

You will have to help me track this bug down, as I am neither using python 2 nor MacOS, so debugging that for me is almost impossible.
I created a new branch "issue17" and changed something that I think could be the problem, but I can't test it for your setting. Could you give that a try, it still runs fine for my setup (Linux, Python 3.5.2)?
Let me know if you need help installing pySMAC from a branch of this git repository.

Best,

Stefan

**Comment by jaanaltosaar** [comment] 2016-07-11 15:59
Thanks @sfalkner!! 

I just tried with Anaconda / Python 3 install from origin/master and it works fine. Unfortunately I really need to use this specifically with 2.7 for a whole host of dependencies. 

Installing from origin/issue17 branch still gives me the same resource error. 

There's an error in the install for both Python 3 origin/master and Python 2.7 origin/issue17: http://pastebin.com/raw/hfjxmf6z

```
byte-compiling build/bdist.macosx-10.6-x86_64/egg/pysmac/utils/smac_input_readers.py to smac_input_readers.pyc
  File "build/bdist.macosx-10.6-x86_64/egg/pysmac/utils/smac_input_readers.py", line 69
    def write_pcs(pcs_filename, parameters, forbiddens, conditionals)
                                                                    ^
SyntaxError: invalid syntax

byte-compiling build/bdist.macosx-10.6-x86_64/egg/pysmac/utils/smac_output_readers.py to smac_output_readers.pyc
```

I fixed this line (adding a colon to L69 in `pysmac/utils/smac_input_readers.py`) and reinstalled, but still get the resource error.

**Comment by sfalkner** [comment] 2016-07-11 18:35
Thanks for pointing out the missing colon, I changed that in the repo. I also tried something different on the 'issue17' branch. Could you check again?
The problem is related to sockets (yes the Java SMAC and the python interface communicate using network sockets, don't ask). The problem is well known on BSD and MacOS, and usually fixed with setting the sockets to blocking, which I did now. If that doesn't help, the next solution would be to catch that exception in 'pysmac/remote_smac.py' around line 200. Let me know if the change right now does not work. I can then try to catch the 'timeout' exception and keep trying, but I would rather not.

**Comment by jaanaltosaar** [comment] 2016-07-11 21:37
Thanks! Just tried it; unfortunately now it hangs:

```
jaana@jaana  ~/projects/pySMAC/examples  ➦ 14ae4be  python branin_example.py
^CTraceback (most recent call last):
  File "build/bdist.macosx-10.6-x86_64/egg/pysmac/remote_smac.py", line 275, in remote_smac_function
    config_dict = smac.next_configuration()
  File "build/bdist.macosx-10.6-x86_64/egg/pysmac/remote_smac.py", line 194, in next_configuration
    self.__conn, addr = self.__sock.accept()
  File "/Users/jaana/anaconda2/lib/python2.7/socket.py", line 206, in accept
    sock, addr = self._sock.accept()
KeyboardInterrupt
Traceback (most recent call last):
  File "branin_example.py", line 52, in <module>
    parameter_definition) # the parameter dictionary
  File "build/bdist.macosx-10.6-x86_64/egg/pysmac/optimizer.py", line 290, in minimize
  File "/Users/jaana/anaconda2/lib/python2.7/multiprocessing/pool.py", line 251, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/Users/jaana/anaconda2/lib/python2.7/multiprocessing/pool.py", line 561, in get
    self.wait(timeout)
  File "/Users/jaana/anaconda2/lib/python2.7/multiprocessing/pool.py", line 556, in wait
    self._cond.wait(timeout)
  File "/Users/jaana/anaconda2/lib/python2.7/threading.py", line 340, in wait
    waiter.acquire()
KeyboardInterrupt
 ✘ jaana@jaana  ~/projects/pySMAC/examples  ➦ 14ae4be ● 
```

Happy to keep trying - catching the timeout sounds promising. It might be a race condition in multiprocessing.

In the past when I ran into issues with multiprocessing I switched to joblib (joblib.Parallel) which helped avoid these issues (it has much better management of threads/memory/etc). It's just a wrapper on top of multiprocessing. If this is easy to replace in your code it might solve it.

**Comment by sfalkner** [comment] 2016-07-12 19:02
I just commit something that tries to catch that stupid EAGAIN error, so please give that a try.
The problem is, I think, socket related. For some reason, these are handled differently in BSD/MacOS and Linux. The thrown exception is just the message 'the socket from which you tried to read is currently empty, please try again.' If you google that it seems to be a known issue. I am glad that it seems fixed in python 3, but that doesn't help you right now.

**Comment by jaanaltosaar** [comment] 2016-07-12 21:04
Thanks! Just tried it:

```
jaana@jaana  ~/projects/pySMAC/examples  ➦ fecd8a4 ●  python branin_example.py
Traceback (most recent call last):
  File "build/bdist.macosx-10.6-x86_64/egg/pysmac/remote_smac.py", line 279, in remote_smac_function
    config_dict = smac.next_configuration()
  File "build/bdist.macosx-10.6-x86_64/egg/pysmac/remote_smac.py", line 208, in next_configuration
    if e.args[0] == errno.EAGAIN:
NameError: global name 'errno' is not defined
Lowest function value found: 179769313486231570814527423731704356798070567525844996598917476803157260780028538760589558632766878171540458953514382464234321326889464182768467546703537516986049910576551282076245490090389328944075868508455133942304583236903222948165808559332123348274797826204144723168738177180919299881250404026184124858368.000000
Parameter setting {'x2': -1.0, 'x3': 1, 'x1': 1.0}
```

**Comment by sfalkner** [comment] 2016-07-14 19:59
Sorry for the delay. That was a stupid missing import statement, my bad. Could you try again?

**Comment by jaanaltosaar** [comment] 2016-07-14 20:30
No worries! Just pulled:

```
~/projects/pySMAC/examples  ➦ fecd8a4 ●  python branin_example.py
Traceback (most recent call last):
  File "build/bdist.macosx-10.6-x86_64/egg/pysmac/remote_smac.py", line 279, in remote_smac_function
    config_dict = smac.next_configuration()
  File "build/bdist.macosx-10.6-x86_64/egg/pysmac/remote_smac.py", line 208, in next_configuration
    if e.args[0] == errno.EAGAIN:
NameError: global name 'errno' is not defined
Lowest function value found: 179769313486231570814527423731704356798070567525844996598917476803157260780028538760589558632766878171540458953514382464234321326889464182768467546703537516986049910576551282076245490090389328944075868508455133942304583236903222948165808559332123348274797826204144723168738177180919299881250404026184124858368.000000
Parameter setting {'x2': -1.0, 'x3': 1, 'x1': 1.0}
```

**Comment by sfalkner** [comment] 2016-07-14 20:55
Well, this is embarrassing. I didn't actually push, just committed _shame_. Could you try one more time?

**Comment by jaanaltosaar** [comment] 2016-07-14 22:24
Happens to me all the time! Now a popup comes up: `Do you want the application “python2.7” to accept incoming network connections?`, I click allow, and then it hangs:

```
 ✘ jaana@jaana  ~/projects/pySMAC/examples  ➦ 1af8d1c ●  python branin_example.py
^CTraceback (most recent call last):
  File "build/bdist.macosx-10.6-x86_64/egg/pysmac/remote_smac.py", line 280, in remote_smac_function
    config_dict = smac.next_configuration()
  File "build/bdist.macosx-10.6-x86_64/egg/pysmac/remote_smac.py", line 194, in next_configuration
    self.__conn, addr = self.__sock.accept()
  File "/Users/jaana/anaconda2/lib/python2.7/socket.py", line 206, in accept
    sock, addr = self._sock.accept()
KeyboardInterrupt
Traceback (most recent call last):
  File "branin_example.py", line 54, in <module>
    parameter_definition) # the parameter dictionary
  File "build/bdist.macosx-10.6-x86_64/egg/pysmac/optimizer.py", line 290, in minimize
  File "/Users/jaana/anaconda2/lib/python2.7/multiprocessing/pool.py", line 251, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/Users/jaana/anaconda2/lib/python2.7/multiprocessing/pool.py", line 561, in get
    self.wait(timeout)
  File "/Users/jaana/anaconda2/lib/python2.7/multiprocessing/pool.py", line 556, in wait
    self._cond.wait(timeout)
  File "/Users/jaana/anaconda2/lib/python2.7/threading.py", line 340, in wait
    waiter.acquire()
KeyboardInterrupt
```

**Comment by sfalkner** [comment] 2016-07-15 20:01
Could you please pull again and run the Branin example? I enabled debugging output, so the terminal won't stay still, but if you could post the output, I could see what is going on. Thanks!

**Comment by jaanaltosaar** [comment] 2016-07-15 21:31
Yep, of course! Here it is:

```
jaana@jaana-macbookair  ~/projects/pySMAC/examples  ➦ d796b18  python branin_example.py
[DEBUG/MainProcess] Writing output into: /var/folders/m6/48h6pb_s7c1bgjk5l37_dyd8009knd/T/tmpYQQUe9
[DEBUG/MainProcess] created semlock with handle 6
[DEBUG/MainProcess] created semlock with handle 7
[DEBUG/MainProcess] created semlock with handle 10
[DEBUG/MainProcess] created semlock with handle 11
[DEBUG/MainProcess] added worker
[INFO/NoDaemonPoolWorker-1] child process calling self.run()
[DEBUG/MainProcess] SMAC classpath: /Users/jaana/.python-eggs/pysmac-0.9.1-py2.7.egg-tmp/pysmac/smac/smac-v2.10.03-master-778/lib/aeatk-src.jar:/Users/jaana/.python-eggs/pysmac-0.9.1-py2.7.egg-tmp/pysmac/smac/smac-v2.10.03-master-778/lib/aeatk.jar:/Users/jaana/.python-eggs/pysmac-0.9.1-py2.7.egg-tmp/pysmac/smac/smac-v2.10.03-master-778/lib/commons-collections-3.2.1-sources.jar:/Users/jaana/.python-eggs/pysmac-0.9.1-py2.7.egg-tmp/pysmac/smac/smac-v2.10.03-master-778/lib/commons-collections-3.2.1.jar:/Users/jaana/.python-eggs/pysmac-0.9.1-py2.7.egg-tmp/pysmac/smac/smac-v2.10.03-master-778/lib/commons-io-2.1.jar:/Users/jaana/.python-eggs/pysmac-0.9.1-py2.7.egg-tmp/pysmac/smac/smac-v2.10.03-master-778/lib/commons-math-2.2.jar:/Users/jaana/.python-eggs/pysmac-0.9.1-py2.7.egg-tmp/pysmac/smac/smac-v2.10.03-master-778/lib/commons-math3-3.3.jar:/Users/jaana/.python-eggs/pysmac-0.9.1-py2.7.egg-tmp/pysmac/smac/smac-v2.10.03-master-778/lib/DomainInter.jar:/Users/jaana/.python-eggs/pysmac-0.9.1-py2.7.egg-tmp/pysmac/smac/smac-v2.10.03-master-778/lib/exp4j-0.3.10.jar:/Users/jaana/.python-eggs/pysmac-0.9.1-py2.7.egg-tmp/pysmac/smac/smac-v2.10.03-master-778/lib/exp4j-0.4.3.BETA-3.jar:/Users/jaana/.python-eggs/pysmac-0.9.1-py2.7.egg-tmp/pysmac/smac/smac-v2.10.03-master-778/lib/fastrf-src.jar:/Users/jaana/.python-eggs/pysmac-0.9.1-py2.7.egg-tmp/pysmac/smac/smac-v2.10.03-master-778/lib/fastrf.jar:/Users/jaana/.python-eggs/pysmac-0.9.1-py2.7.egg-tmp/pysmac/smac/smac-v2.10.03-master-778/lib/guava-14.0.1.jar:/Users/jaana/.python-eggs/pysmac-0.9.1-py2.7.egg-tmp/pysmac/smac/smac-v2.10.03-master-778/lib/jackson-annotations-2.3.1.jar:/Users/jaana/.python-eggs/pysmac-0.9.1-py2.7.egg-tmp/pysmac/smac/smac-v2.10.03-master-778/lib/jackson-core-2.3.1.jar:/Users/jaana/.python-eggs/pysmac-0.9.1-py2.7.egg-tmp/pysmac/smac/smac-v2.10.03-master-778/lib/jackson-databind-2.3.1.jar:/Users/jaana/.python-eggs/pysmac-0.9.1-py2.7.egg-tmp/pysmac/smac/smac-v2.10.03-master-778/lib/Jama-1.0.2.jar:/Users/jaana/.python-eggs/pysmac-0.9.1-py2.7.egg-tmp/pysmac/smac/smac-v2.10.03-master-778/lib/jcip-annotations-src.jar:/Users/jaana/.python-eggs/pysmac-0.9.1-py2.7.egg-tmp/pysmac/smac/smac-v2.10.03-master-778/lib/jcip-annotations.jar:/Users/jaana/.python-eggs/pysmac-0.9.1-py2.7.egg-tmp/pysmac/smac/smac-v2.10.03-master-778/lib/jcommander.jar:/Users/jaana/.python-eggs/pysmac-0.9.1-py2.7.egg-tmp/pysmac/smac/smac-v2.10.03-master-778/lib/jmatharray.jar:/Users/jaana/.python-eggs/pysmac-0.9.1-py2.7.egg-tmp/pysmac/smac/smac-v2.10.03-master-778/lib/logback-access-1.1.2.jar:/Users/jaana/.python-eggs/pysmac-0.9.1-py2.7.egg-tmp/pysmac/smac/smac-v2.10.03-master-778/lib/logback-classic-1.1.2.jar:/Users/jaana/.python-eggs/pysmac-0.9.1-py2.7.egg-tmp/pysmac/smac/smac-v2.10.03-master-778/lib/logback-core-1.1.2.jar:/Users/jaana/.python-eggs/pysmac-0.9.1-py2.7.egg-tmp/pysmac/smac/smac-v2.10.03-master-778/lib/numerics4j-1.3.jar:/Users/jaana/.python-eggs/pysmac-0.9.1-py2.7.egg-tmp/pysmac/smac/smac-v2.10.03-master-778/lib/opencsv-2.3.jar:/Users/jaana/.python-eggs/pysmac-0.9.1-py2.7.egg-tmp/pysmac/smac/smac-v2.10.03-master-778/lib/slf4j-api-1.7.5.jar:/Users/jaana/.python-eggs/pysmac-0.9.1-py2.7.egg-tmp/pysmac/smac/smac-v2.10.03-master-778/lib/smac-src.jar:/Users/jaana/.python-eggs/pysmac-0.9.1-py2.7.egg-tmp/pysmac/smac/smac-v2.10.03-master-778/lib/smac.jar:/Users/jaana/.python-eggs/pysmac-0.9.1-py2.7.egg-tmp/pysmac/smac/smac-v2.10.03-master-778/lib/spi-0.2.4.jar:/Users/jaana/.python-eggs/pysmac-0.9.1-py2.7.egg-tmp/pysmac/smac/smac-v2.10.03-master-778/conf:/Users/jaana/.python-eggs/pysmac-0.9.1-py2.7.egg-tmp/pysmac/smac/smac-v2.10.03-master-778/patches
[DEBUG/NoDaemonPoolWorker-1] picked port 56495
[DEBUG/NoDaemonPoolWorker-1] SMAC command: java -XX:ParallelGCThreads=4 -cp /Users/jaana/.python-eggs/pysmac-0.9.1-py2.7.egg-tmp/pysmac/smac/smac-v2.10.03-master-778/lib/aeatk-src.jar:/Users/jaana/.python-eggs/pysmac-0.9.1-py2.7.egg-tmp/pysmac/smac/smac-v2.10.03-master-778/lib/aeatk.jar:/Users/jaana/.python-eggs/pysmac-0.9.1-py2.7.egg-tmp/pysmac/smac/smac-v2.10.03-master-778/lib/commons-collections-3.2.1-sources.jar:/Users/jaana/.python-eggs/pysmac-0.9.1-py2.7.egg-tmp/pysmac/smac/smac-v2.10.03-master-778/lib/commons-collections-3.2.1.jar:/Users/jaana/.python-eggs/pysmac-0.9.1-py2.7.egg-tmp/pysmac/smac/smac-v2.10.03-master-778/lib/commons-io-2.1.jar:/Users/jaana/.python-eggs/pysmac-0.9.1-py2.7.egg-tmp/pysmac/smac/smac-v2.10.03-master-778/lib/commons-math-2.2.jar:/Users/jaana/.python-eggs/pysmac-0.9.1-py2.7.egg-tmp/pysmac/smac/smac-v2.10.03-master-778/lib/commons-math3-3.3.jar:/Users/jaana/.python-eggs/pysmac-0.9.1-py2.7.egg-tmp/pysmac/smac/smac-v2.10.03-master-778/lib/DomainInter.jar:/Users/jaana/.python-eggs/pysmac-0.9.1-py2.7.egg-tmp/pysmac/smac/smac-v2.10.03-master-778/lib/exp4j-0.3.10.jar:/Users/jaana/.python-eggs/pysmac-0.9.1-py2.7.egg-tmp/pysmac/smac/smac-v2.10.03-master-778/lib/exp4j-0.4.3.BETA-3.jar:/Users/jaana/.python-eggs/pysmac-0.9.1-py2.7.egg-tmp/pysmac/smac/smac-v2.10.03-master-778/lib/fastrf-src.jar:/Users/jaana/.python-eggs/pysmac-0.9.1-py2.7.egg-tmp/pysmac/smac/smac-v2.10.03-master-778/lib/fastrf.jar:/Users/jaana/.python-eggs/pysmac-0.9.1-py2.7.egg-tmp/pysmac/smac/smac-v2.10.03-master-778/lib/guava-14.0.1.jar:/Users/jaana/.python-eggs/pysmac-0.9.1-py2.7.egg-tmp/pysmac/smac/smac-v2.10.03-master-778/lib/jackson-annotations-2.3.1.jar:/Users/jaana/.python-eggs/pysmac-0.9.1-py2.7.egg-tmp/pysmac/smac/smac-v2.10.03-master-778/lib/jackson-core-2.3.1.jar:/Users/jaana/.python-eggs/pysmac-0.9.1-py2.7.egg-tmp/pysmac/smac/smac-v2.10.03-master-778/lib/jackson-databind-2.3.1.jar:/Users/jaana/.python-eggs/pysmac-0.9.1-py2.7.egg-tmp/pysmac/smac/smac-v2.10.03-master-778/lib/Jama-1.0.2.jar:/Users/jaana/.python-eggs/pysmac-0.9.1-py2.7.egg-tmp/pysmac/smac/smac-v2.10.03-master-778/lib/jcip-annotations-src.jar:/Users/jaana/.python-eggs/pysmac-0.9.1-py2.7.egg-tmp/pysmac/smac/smac-v2.10.03-master-778/lib/jcip-annotations.jar:/Users/jaana/.python-eggs/pysmac-0.9.1-py2.7.egg-tmp/pysmac/smac/smac-v2.10.03-master-778/lib/jcommander.jar:/Users/jaana/.python-eggs/pysmac-0.9.1-py2.7.egg-tmp/pysmac/smac/smac-v2.10.03-master-778/lib/jmatharray.jar:/Users/jaana/.python-eggs/pysmac-0.9.1-py2.7.egg-tmp/pysmac/smac/smac-v2.10.03-master-778/lib/logback-access-1.1.2.jar:/Users/jaana/.python-eggs/pysmac-0.9.1-py2.7.egg-tmp/pysmac/smac/smac-v2.10.03-master-778/lib/logback-classic-1.1.2.jar:/Users/jaana/.python-eggs/pysmac-0.9.1-py2.7.egg-tmp/pysmac/smac/smac-v2.10.03-master-778/lib/logback-core-1.1.2.jar:/Users/jaana/.python-eggs/pysmac-0.9.1-py2.7.egg-tmp/pysmac/smac/smac-v2.10.03-master-778/lib/numerics4j-1.3.jar:/Users/jaana/.python-eggs/pysmac-0.9.1-py2.7.egg-tmp/pysmac/smac/smac-v2.10.03-master-778/lib/opencsv-2.3.jar:/Users/jaana/.python-eggs/pysmac-0.9.1-py2.7.egg-tmp/pysmac/smac/smac-v2.10.03-master-778/lib/slf4j-api-1.7.5.jar:/Users/jaana/.python-eggs/pysmac-0.9.1-py2.7.egg-tmp/pysmac/smac/smac-v2.10.03-master-778/lib/smac-src.jar:/Users/jaana/.python-eggs/pysmac-0.9.1-py2.7.egg-tmp/pysmac/smac/smac-v2.10.03-master-778/lib/smac.jar:/Users/jaana/.python-eggs/pysmac-0.9.1-py2.7.egg-tmp/pysmac/smac/smac-v2.10.03-master-778/lib/spi-0.2.4.jar:/Users/jaana/.python-eggs/pysmac-0.9.1-py2.7.egg-tmp/pysmac/smac/smac-v2.10.03-master-778/conf:/Users/jaana/.python-eggs/pysmac-0.9.1-py2.7.egg-tmp/pysmac/smac/smac-v2.10.03-master-778/patches ca.ubc.cs.beta.smac.executors.SMACExecutor --scenario-file /var/folders/m6/48h6pb_s7c1bgjk5l37_dyd8009knd/T/tmpYQQUe9/scenario.dat --tae IPC --ipc-mechanism TCP --ipc-remote-port 56495 --seed 0 --skip-features True --rf-full-tree-bootstrap False --rf-ignore-conditionality False --numPCA 7 --console-log-level INFO --runcount-limit 1000 --intensification-percentage 0.5 --rf-num-trees 10 --abort-on-first-run-crash False --validation False
[DEBUG/NoDaemonPoolWorker-1] Starting SMAC in ICP mode
[DEBUG/NoDaemonPoolWorker-1] Started SMAC subprocess
[DEBUG/NoDaemonPoolWorker-1] trying to retrieve the next configuration from SMAC
[DEBUG/NoDaemonPoolWorker-1] SMAC has not responded yet, but is still alive. Will keep waiting!
[DEBUG/NoDaemonPoolWorker-1] trying to retrieve the next configuration from SMAC
[INFO ] Logging to: /var/folders/m6/48h6pb_s7c1bgjk5l37_dyd8009knd/T/tmpYQQUe9/out/scenario/log-run0.txt
[INFO ] Version of SMAC is v2.10.03-master-778 (3ee628ef9bf2), running on Java HotSpot(TM) 64-Bit Server VM (1.8.0_91) and Mac OS X 10.11.5 (x86_64)
[INFO ] Call String: smac --scenario-file /var/folders/m6/48h6pb_s7c1bgjk5l37_dyd8009knd/T/tmpYQQUe9/scenario.dat --tae IPC --ipc-mechanism TCP --ipc-remote-port 56495 --seed 0 --skip-features True --rf-full-tree-bootstrap False --rf-ignore-conditionality False --numPCA 7 --console-log-level INFO --runcount-limit 1000 --intensification-percentage 0.5 --rf-num-trees 10 --abort-on-first-run-crash False --validation False
[INFO ] Target Algorithm Evaluator making TCP connections to 127.0.0.1:56495.
[INFO ] SMAC started at: Jul 15, 2016 2:30:44 PM. Minimizing mean quality.
[DEBUG/NoDaemonPoolWorker-1] Socket to SMAC process was empty, will continue to wait.
[DEBUG/NoDaemonPoolWorker-1] trying to retrieve the next configuration from SMAC
[DEBUG/NoDaemonPoolWorker-1] SMAC has not responded yet, but is still alive. Will keep waiting!
[DEBUG/NoDaemonPoolWorker-1] trying to retrieve the next configuration from SMAC
[DEBUG/NoDaemonPoolWorker-1] SMAC has not responded yet, but is still alive. Will keep waiting!
[DEBUG/NoDaemonPoolWorker-1] trying to retrieve the next configuration from SMAC
[DEBUG/NoDaemonPoolWorker-1] SMAC has not responded yet, but is still alive. Will keep waiting!
[DEBUG/NoDaemonPoolWorker-1] trying to retrieve the next configuration from SMAC
[DEBUG/NoDaemonPoolWorker-1] SMAC has not responded yet, but is still alive. Will keep waiting!
[DEBUG/NoDaemonPoolWorker-1] trying to retrieve the next configuration from SMAC
[DEBUG/NoDaemonPoolWorker-1] SMAC has not responded yet, but is still alive. Will keep waiting!
[DEBUG/NoDaemonPoolWorker-1] trying to retrieve the next configuration from SMAC
[DEBUG/NoDaemonPoolWorker-1] SMAC has not responded yet, but is still alive. Will keep waiting!
[DEBUG/NoDaemonPoolWorker-1] trying to retrieve the next configuration from SMAC
[DEBUG/NoDaemonPoolWorker-1] SMAC has not responded yet, but is still alive. Will keep waiting!
[DEBUG/NoDaemonPoolWorker-1] trying to retrieve the next configuration from SMAC
[DEBUG/NoDaemonPoolWorker-1] SMAC has not responded yet, but is still alive. Will keep waiting!
[DEBUG/NoDaemonPoolWorker-1] trying to retrieve the next configuration from SMAC
[DEBUG/NoDaemonPoolWorker-1] SMAC has not responded yet, but is still alive. Will keep waiting!
[DEBUG/NoDaemonPoolWorker-1] trying to retrieve the next configuration from SMAC
[DEBUG/NoDaemonPoolWorker-1] SMAC has not responded yet, but is still alive. Will keep waiting!
[DEBUG/NoDaemonPoolWorker-1] trying to retrieve the next configuration from SMAC
[DEBUG/NoDaemonPoolWorker-1] SMAC has not responded yet, but is still alive. Will keep waiting!
[DEBUG/NoDaemonPoolWorker-1] trying to retrieve the next configuration from SMAC
[DEBUG/NoDaemonPoolWorker-1] SMAC has not responded yet, but is still alive. Will keep waiting!
[DEBUG/NoDaemonPoolWorker-1] trying to retrieve the next configuration from SMAC
[DEBUG/NoDaemonPoolWorker-1] SMAC has not responded yet, but is still alive. Will keep waiting!
[DEBUG/NoDaemonPoolWorker-1] trying to retrieve the next configuration from SMAC
[DEBUG/NoDaemonPoolWorker-1] SMAC has not responded yet, but is still alive. Will keep waiting!
[DEBUG/NoDaemonPoolWorker-1] trying to retrieve the next configuration from SMAC
[DEBUG/NoDaemonPoolWorker-1] SMAC has not responded yet, but is still alive. Will keep waiting!
[DEBUG/NoDaemonPoolWorker-1] trying to retrieve the next configuration from SMAC
[DEBUG/NoDaemonPoolWorker-1] SMAC has not responded yet, but is still alive. Will keep waiting!
[DEBUG/NoDaemonPoolWorker-1] trying to retrieve the next configuration from SMAC
[DEBUG/NoDaemonPoolWorker-1] SMAC has not responded yet, but is still alive. Will keep waiting!
[DEBUG/NoDaemonPoolWorker-1] trying to retrieve the next configuration from SMAC
[DEBUG/NoDaemonPoolWorker-1] SMAC has not responded yet, but is still alive. Will keep waiting!
[DEBUG/NoDaemonPoolWorker-1] trying to retrieve the next configuration from SMAC
^CTraceback (most recent call last):
  File "build/bdist.macosx-10.6-x86_64/egg/pysmac/remote_smac.py", line 280, in remote_smac_function
    config_dict = smac.next_configuration()
  File "build/bdist.macosx-10.6-x86_64/egg/pysmac/remote_smac.py", line 194, in next_configuration
    self.__conn, addr = self.__sock.accept()
  File "/Users/jaana/anaconda2/lib/python2.7/socket.py", line 206, in accept
    sock, addr = self._sock.accept()
KeyboardInterrupt
[DEBUG/NoDaemonPoolWorker-1] SMAC had to be terminated
Traceback (most recent call last):
  File "branin_example.py", line 54, in <module>
    parameter_definition) # the parameter dictionary
  File "build/bdist.macosx-10.6-x86_64/egg/pysmac/optimizer.py", line 290, in minimize
  File "/Users/jaana/anaconda2/lib/python2.7/multiprocessing/pool.py", line 251, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/Users/jaana/anaconda2/lib/python2.7/multiprocessing/pool.py", line 561, in get
    self.wait(timeout)
  File "/Users/jaana/anaconda2/lib/python2.7/multiprocessing/pool.py", line 556, in wait
    self._cond.wait(timeout)
  File "/Users/jaana/anaconda2/lib/python2.7/threading.py", line 340, in wait
    waiter.acquire()
KeyboardInterrupt
[INFO/MainProcess] process shutting down
[DEBUG/MainProcess] running all "atexit" finalizers with priority >= 0
[SUBDEBUG/MainProcess] calling <Finalize object, callback=_terminate_pool, args=(<Queue.Queue instance at 0x108593758>, <multiprocessing.queues.SimpleQueue object at 0x108466b10>, <multiprocessing.queues.SimpleQueue object at 0x108591650>, [<NoDaemonProcess(NoDaemonPoolWorker-1, started)>], <Thread(Thread-1, started daemon 123145306509312)>, <Thread(Thread-2, started daemon 123145310715904)>, <Thread(Thread-3, started daemon 123145314922496)>, {}), exitprority=15>
[SUBDEBUG/MainProcess] finalizer calling <bound method type._terminate_pool of <class 'pysmac.utils.multiprocessing_wrapper.MyPool'>> with args (<Queue.Queue instance at 0x108593758>, <multiprocessing.queues.SimpleQueue object at 0x108466b10>, <multiprocessing.queues.SimpleQueue object at 0x108591650>, [<NoDaemonProcess(NoDaemonPoolWorker-1, started)>], <Thread(Thread-1, started daemon 123145306509312)>, <Thread(Thread-2, started daemon 123145310715904)>, <Thread(Thread-3, started daemon 123145314922496)>, {}) and kwargs {}
[DEBUG/MainProcess] finalizing pool
[DEBUG/MainProcess] helping task handler/workers to finish
[DEBUG/MainProcess] removing tasks from inqueue until task handler finished
[DEBUG/MainProcess] worker handler exiting
[DEBUG/MainProcess] task handler got sentinel
[DEBUG/MainProcess] task handler sending sentinel to result handler
[DEBUG/MainProcess] task handler sending sentinel to workers
[DEBUG/MainProcess] result handler got sentinel
[DEBUG/NoDaemonPoolWorker-1] worker got sentinel -- exiting
[DEBUG/MainProcess] ensuring that outqueue is not full
[DEBUG/NoDaemonPoolWorker-1] worker exiting after 1 tasks
[INFO/NoDaemonPoolWorker-1] process shutting down
[DEBUG/MainProcess] task handler exiting
[DEBUG/NoDaemonPoolWorker-1] running all "atexit" finalizers with priority >= 0
[DEBUG/MainProcess] result handler exiting: len(cache)=0, thread._state=2
[DEBUG/NoDaemonPoolWorker-1] running the remaining "atexit" finalizers
[DEBUG/MainProcess] joining worker handler
[INFO/NoDaemonPoolWorker-1] process exiting with exitcode 0
[DEBUG/MainProcess] terminating workers
[DEBUG/MainProcess] joining task handler
[DEBUG/MainProcess] joining result handler
[DEBUG/MainProcess] joining pool workers
[DEBUG/MainProcess] cleaning up worker 74663
[DEBUG/MainProcess] running the remaining "atexit" finalizers
```

**Comment by sfalkner** [comment] 2016-07-16 20:47
This is very surprising/confusing. I pushed some change that extends the lifetime of the used socket. Could you run the Branin example again with that?

**Comment by jaanaltosaar** [comment] 2016-07-17 17:05
Awesome! There was a tiny indent needed here: `pysmac/remote_smac.py`, line 190.

Looks like it is working - I ran the example for 10 iterations :)

http://pastebin.com/iHi1ZL3y

Thanks so much for all your help. I'll be sure to send you the project when it's done, pySMAC is a crucial aspect of it!

edit: reopening as it hasn't been merged yet.

**Comment by sfalkner** [comment] 2016-07-17 20:25
You are welcome! Glad we could figure it out. I merged the changes into master. I hopefully fixed the indent (stupid tabs vs space debate =) ).
Please keep me updated on whatever you use pySMAC for. We are always curious to see what applications arise.

**Closed as completed by sfalkner** 2016-07-17 20:25 UTC
